server:
  port: 8080


chat:
  database:
    user: root
    pwd: chatdev
    url: 172.20.0.2
    db: withchat

  minio:
    bucket: withchat-dev
    access: Pqag5oXJTtYmKebKWVEj
    secret: Rk3OoMU1Ot5EYpCu0GzLebeFbDirTvF5MOPRBxV0
    endpoint: http://172.20.0.3:9000
